version: '3'
services:
  web:
    container_name: pgr
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/tcc'
      - './db.sqlite3:/tcc/db.sqlite3'
    ports:
      - '8000:8000'

  db:
    container_name: pgr_db
    image: alpine
    volumes:
      - './db.sqlite3:/tcc/db.sqlite3'
    command: tail -f /dev/null
