# Generated by Django 3.1.14 on 2023-03-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoRiscos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacaoRisco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidasControle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='exposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelExposicao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='gravidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelGravidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='probabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelProbabilidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='risco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelRisco', models.CharField(max_length=200)),
            ],
        ),
    ]
