# Generated by Django 3.2.18 on 2023-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='setor',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_funcionarios',
            field=models.IntegerField(),
        ),
    ]
