# Generated by Django 3.1.14 on 2023-03-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('funcao', models.CharField(blank=True, max_length=200, null=True)),
                ('cboFuncao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmpresa', models.CharField(blank=True, max_length=200, null=True)),
                ('responsavelEmpresa', models.CharField(blank=True, max_length=200, null=True)),
                ('numeroFuncionarios', models.CharField(blank=True, max_length=200, null=True)),
                ('setor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatoresRisco', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoRisco', models.CharField(blank=True, max_length=200, null=True)),
                ('descricaoPerigos', models.CharField(blank=True, max_length=200, null=True)),
                ('descricaoRisco', models.CharField(blank=True, max_length=200, null=True)),
                ('possiveisLesoes', models.CharField(blank=True, max_length=200, null=True)),
                ('fonteCircunstancias', models.CharField(blank=True, max_length=200, null=True)),
                ('medidasImplementadas', models.CharField(blank=True, max_length=200, null=True)),
                ('tempoExposicao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oque', models.CharField(blank=True, max_length=200, null=True)),
                ('porque', models.CharField(blank=True, max_length=200, null=True)),
                ('quando', models.CharField(blank=True, max_length=200, null=True)),
                ('quem', models.CharField(blank=True, max_length=200, null=True)),
                ('onde', models.CharField(blank=True, max_length=200, null=True)),
                ('como', models.CharField(blank=True, max_length=200, null=True)),
                ('quanto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('matricula', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('funcao', models.CharField(blank=True, max_length=200, null=True)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargos')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='classificacao',
        ),
        migrations.DeleteModel(
            name='controle',
        ),
        migrations.DeleteModel(
            name='exposicao',
        ),
        migrations.DeleteModel(
            name='gravidade',
        ),
        migrations.DeleteModel(
            name='probabilidade',
        ),
        migrations.DeleteModel(
            name='risco',
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='classificacaoRisco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='medidasControle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='nivelExposicao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='nivelGravidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='nivelProbabilidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoriscos',
            name='nivelRisco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuarioinventario',
            name='idAvaliacaoRiscos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.avaliacaoriscos', verbose_name='avaliacaoriscos'),
        ),
        migrations.AddField(
            model_name='usuarioinventario',
            name='idInventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.inventario', verbose_name='inventario'),
        ),
        migrations.AddField(
            model_name='usuarioinventario',
            name='idPlanoAcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.planoacao', verbose_name='planoacao'),
        ),
        migrations.AddField(
            model_name='usuarioinventario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario', verbose_name='usuario'),
        ),
    ]
