# Generated by Django 3.1.14 on 2023-03-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20230309_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaliacaoRiscos',
            new_name='AvaliacaoRisco',
        ),
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cargo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
    ]
