# Generated by Django 3.2.18 on 2023-03-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20230323_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_classificacao_risco',
            new_name='classificacao_risco',
        ),
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_medidas_controle',
            new_name='medidas_controle',
        ),
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_nivel_exposicao',
            new_name='nivel_exposicao',
        ),
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_nivel_gravidade',
            new_name='nivel_gravidade',
        ),
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_nivel_probabilidade',
            new_name='nivel_probabilidade',
        ),
        migrations.RenameField(
            model_name='avaliacaorisco',
            old_name='id_nivel_risco',
            new_name='nivel_risco',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='responsavel_empresa',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_lesao',
            new_name='descricao_lesao',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_perigo',
            new_name='descricao_perigo',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_fonte',
            new_name='fonte_risco',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_medidas',
            new_name='medidas_implementadas',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_tempo_exposicao',
            new_name='tempo_exposicao',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_risco',
            new_name='tipo_risco',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_setor',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='usuarioinventario',
            old_name='id_inventario',
            new_name='inventario',
        ),
        migrations.RenameField(
            model_name='usuarioinventario',
            old_name='id_plano_acao',
            new_name='plano_acao',
        ),
        migrations.RenameField(
            model_name='usuarioinventario',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='descricaoperigo',
            name='id_perigo',
        ),
        migrations.RemoveField(
            model_name='fonterisco',
            name='id_fonte_risco',
        ),
        migrations.RemoveField(
            model_name='lesoes',
            name='id_lesao',
        ),
        migrations.RemoveField(
            model_name='tiporisco',
            name='id_risco',
        ),
    ]
