# Generated by Django 3.2.18 on 2023-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20230325_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name_plural': 'Funcoes'},
        ),
        migrations.AlterField(
            model_name='medidascontrole',
            name='medidas_controle',
            field=models.CharField(choices=[('A', 'Aceitável'), ('I', 'Ineficiente'), ('D', 'Deficiente'), ('MD', 'Muito Deficiente'), ('DT', 'Deficiência Total')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medidascontrole',
            name='nmc',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('10', '10'), ('14', '14')], max_length=200),
        ),
    ]
