# Generated by Django 3.2.18 on 2023-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20230326_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name_plural': 'funcoes'},
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='ne',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('10', '10'), ('14', '14')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='nivel_exposicao',
            field=models.CharField(choices=[('A', 'Aceitável'), ('I', 'Ineficiente'), ('D', 'Deficiente'), ('MD', 'Muito Deficiente'), ('DT', 'Deficiência Total')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='ng',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('10', '10'), ('14', '14')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='nivel_gravidade',
            field=models.CharField(choices=[('A', 'Aceitável'), ('I', 'Ineficiente'), ('D', 'Deficiente'), ('MD', 'Muito Deficiente'), ('DT', 'Deficiência Total')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='nivel_probabilidade',
            field=models.CharField(choices=[('A', 'Aceitável'), ('I', 'Ineficiente'), ('D', 'Deficiente'), ('MD', 'Muito Deficiente'), ('DT', 'Deficiência Total')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='np',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('10', '10'), ('14', '14')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelrisco',
            name='nivel_risco',
            field=models.CharField(choices=[('A', 'Aceitável'), ('I', 'Ineficiente'), ('D', 'Deficiente'), ('MD', 'Muito Deficiente'), ('DT', 'Deficiência Total')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tempoexposicao',
            name='tempo_exposicao',
            field=models.CharField(choices=[('0', 'Até 1 hora por dia'), ('1', 'Até 2 horas por dia'), ('2', 'Até 4 horas por dia'), ('3', 'Até 6 horas por dia'), ('4', 'Até 8 horas por dia')], max_length=200),
        ),
    ]
