# Generated by Django 3.2.18 on 2023-03-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20230327_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaorisco',
            name='classificacao_risco',
            field=models.CharField(choices=[('C', 'Crítico'), ('A', 'Alto'), ('M', 'Moderado'), ('B', 'Baixo'), ('I', 'Irrelevante')], max_length=200),
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='nr',
            field=models.CharField(choices=[('10850', '3360 a 10850'), ('3100', '1240 a 3100'), ('1200', '360 a 1200'), ('300', '90 a 300'), ('80', '10 a 80')], max_length=200),
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='significado',
            field=models.CharField(choices=[('10850', 'Situação CRITÍCA'), ('10850', 'Intervenção imediata'), ('10850', 'Isolar o perigo até serem adaptadas às medidas de controle'), ('3100', 'Situação a CORRIGIR'), ('3100', 'Adaptar medidas de controle enquanto a situação perigosa não for eliminada ou reduzida'), ('1200', 'Situação a MELHORAR'), ('1200', 'Deverão ser elaborados planos, programas ou procedimentos, documentados de intervenção'), ('300', 'MELHORAR SE POSSÍVEL, justificando a intervenção'), ('80', 'Intervir apenas se uma análise mais pormenorizada o justificar')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medidascontrole',
            name='significado',
            field=models.CharField(choices=[('1', 'Não Foram detectadas anomalias'), ('1', 'O perigo está controlado'), ('2', 'Foram detectados fatores de risco de menor importancia'), ('2', 'O dano pode ocorrer algumas vezes'), ('6', 'Foram detectados alguns fatores de risco significativos'), ('6', 'As medidas preventivas existentes tem sua eficávia reduzida'), ('10', 'Foram detectados fatores de risco significativos'), ('10', 'As medidas preventivas existentes são ineficazes'), ('10', 'O dano ocorerá na maior parte das circunstâncias'), ('14', 'Medidas preventivas inexistentes ou desadequadas'), ('14', 'São esperados danos na maior parte das situações')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='ne',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='nivel_exposicao',
            field=models.CharField(choices=[('E', 'Exporádica'), ('P', 'Pouco Frequente'), ('O', 'Ocasional'), ('F', 'Frequente'), ('C', 'Continuada')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='significado',
            field=models.CharField(choices=[('1', 'Uma vez por ano, por pouco tempo(minutos)'), ('2', 'Algumas vezes por ano e por período de tempo determinado'), ('3', 'Algumas vezes por mês'), ('4', 'Várias vezes durante o período laboral, ainda que com tempos curtos'), ('4', 'Várias vezes por semana ou diário'), ('5', 'Várias vezes por dia com tempo prolongado ou continuamente')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='ng',
            field=models.CharField(choices=[('10', '10'), ('25', '25'), ('60', '60'), ('90', '90'), ('155', '155')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='nivel_gravidade',
            field=models.CharField(choices=[('I', 'Insignificante'), ('L', 'Leve'), ('M', 'Moderado'), ('G', 'Grave'), ('M', 'Mortal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='significado',
            field=models.CharField(choices=[('10', 'Não há danos pessoais'), ('25', 'Pequenas lesões que não requerem hospitalização. Apenas primeiros socorros'), ('60', 'Lesões com incapacidade transitória. REquerem tratamento médico'), ('90', 'Lesões graves que podem ser irreparáveis'), ('155', 'Morte ou incapacidade permanente')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='nivel_probabilidade',
            field=models.CharField(choices=[('MB', 'Muito Baixa'), ('PF', 'Pouco Frequente'), ('M', 'Média'), ('A', 'Alta'), ('MA', 'Muito Alta')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='np',
            field=models.CharField(choices=[('1', '1 a 3'), ('4', '4 a 6'), ('8', '8 a 20'), ('24', '24 a 30'), ('40', '40 a 70')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='significado',
            field=models.CharField(choices=[('1', 'Não é de se esperar que a situação perigosa se materialize, ainda que possa ser concebida'), ('4', 'A materialização da situação perigosa pode ocorrer'), ('8', 'A materialização da situação perigosa é passível de ocorrer pelo menos uma vez com danos'), ('24', 'A materizalização da situação perigosa pode ocorrer várias vezes durante o peródo de trabalho'), ('40', 'Normalmente a materizalização da situação perigosa ocorre com frequência')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nivelrisco',
            name='nivel_risco',
            field=models.CharField(max_length=20),
        ),
    ]
