# Generated by Django 3.1.14 on 2023-04-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20230327_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinventario',
            name='plano_acao',
        ),
        migrations.AlterField(
            model_name='avaliacaorisco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classificacaorisco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descricaoperigo',
            name='descricao_perigo',
            field=models.CharField(choices=[(200004300, 'Impacto de pessoa contra objeto parado'), (200004600, 'Impacto de pessoa contra objeto em movimento'), (200008300, 'Impacto sofrido por pessoa de objeto que cai'), (200008600, 'Impacto sofrido por pessoa de objeto projetado'), (200008900, 'Impacto sofrido por pessoa, NIC'), (200012200, 'Queda de pessoa com diferença de nível de andaime, passagem, plataforma, etc.'), (200012300, 'Queda de pessoa com diferença de nível de escada móvel ou fixada cujos degraus'), (200012400, 'Queda de pessoa com diferença de nível de material empilhado'), (200012500, 'Queda de pessoa com diferença de nível de veículo'), (200012600, 'Queda de pessoa com diferença de nível em escada permanente'), (200012700, 'Queda de pessoa com diferença de nível em poço, escavação, abertura no piso, etc.'), (200012900, 'Queda de pessoa com diferença de nível, NIC'), (200016300, 'Queda de pessoa em mesmo nível em passagem ou superfície de sustentação'), (200016600, 'Queda de pessoa em mesmo nível sobre ou contra alguma coisa'), (200016900, 'Queda de pessoa em mesmo nível, NIC'), (200020100, 'Aprisionamento em, sobre ou entre objetos em movimento convergente'), (200020300, 'Aprisionamento em, sobre ou entre objeto parado e outro em movimento'), (200020500, 'Aprisionamento em, sobre ou entre dois ou mais objetos em movimento'), (200020700, 'Aprisionamento em, sobre ou entre desabamento ou desmoronamento'), (200020900, 'Aprisionamento em, sob ou entre, NIC'), (200024300, 'Atrito ou abrasão por encostar, pisar, ajoelhar ou sentar em objeto'), (200024400, 'Atrito ou abrasão por manusear objeto'), (200024500, 'Atrito ou abrasão por objeto em vibração'), (200024600, 'Atrito ou abrasão por corpo estranho no olho'), (200024700, 'Atrito ou abrasão por compressão repetitiva'), (200024900, 'Atrito ou abrasão, NIC'), (200028300, 'Reação do corpo a movimento involuntário'), (200028600, 'Reação do corpo a movimento voluntário'), (200032200, 'Esforço excessivo ao erguer objeto'), (200032400, 'Esforço excessivo ao empurrar ou puxar objeto'), (200032600, 'Esforço excessivo ao manejar, sacudir ou arremessar objeto'), (200032900, 'Esforço excessivo, NIC'), (200036000, 'Elétrica, exposição a energia'), (200040300, 'Temperatura muito alta, contato com objeto ou substância a'), (200040600, 'Temperatura muito baixa, contato com objeto ou substância a'), (200044300, 'Temperatura ambiente elevada, exposição a'), (200044600, 'Temperatura ambiente baixa, exposição a'), (200048200, 'Inalação de substância cáustica, tóxica ou nociva'), (200048400, 'Ingestão de substância cáustica'), (200048600, 'Absorção de substância cáustica'), (200048900, 'Inalação, ingestão ou absorção, NIC'), (200052000, 'Imersão'), (200056000, 'Radiação não ionizante, exposição a'), (200060000, 'Radiação ionizante, exposição a'), (200064000, 'Ruído, exposição a'), (200068000, 'Vibração, exposição a'), (200072000, 'Pressão ambiente, exposição a'), (200072300, 'Exposição à pressão ambiente elevada'), (200072600, 'Exposição à pressão ambiente baixa'), (200076200, 'Poluição da água, ação da (exposição à poluição da água)'), (200076400, 'Poluição do ar, ação da (exposição à poluição do ar)'), (200076600, 'Poluição do solo, ação da (exposição à poluição do solo)'), (200076900, 'Poluição, NIC, exposição a (exposição à poluição, NIC)'), (200080200, 'Ataque de ser vivo por mordedura, picada, chifrada, coice, etc.'), (200080400, 'Ataque de ser vivo com peçonha'), (200080600, 'Ataque de ser vivo com transmissão de doença'), (200080900, 'Ataque de ser vivo, NIC'), (209000000, 'Tipo, NIC  '), (209500000, 'Tipo inexistente')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='descricaoperigo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fonterisco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesoes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medidascontrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medidasimplementadas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nivelexposicao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nivelgravidade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nivelprobabilidade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nivelrisco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='quando',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tempoexposicao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiporisco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarioinventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UsuarioPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.planoacao', verbose_name='planoacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario', verbose_name='usuario')),
            ],
        ),
    ]
