# Generated by Django 4.2.1 on 2023-05-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempoexposicao',
            options={'ordering': ['tempo_exposicao'], 'verbose_name': 'tempo_exposicao', 'verbose_name_plural': 'tempos_exposicao'},
        ),
    ]
