# Generated by Django 4.2.1 on 2023-05-17 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empregadoinventario',
            options={'verbose_name_plural': 'Empregado x Inventário'},
        ),
        migrations.AlterModelOptions(
            name='empregadoplano',
            options={'verbose_name_plural': 'Empregados x Planos de Ação '},
        ),
        migrations.RemoveField(
            model_name='funcao',
            name='empresa',
        ),
    ]
