# Generated by Django 4.2.1 on 2023-05-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgr', '0002_alter_empregadoinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_empresa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcao',
            old_name='funcao',
            new_name='nome',
        ),
    ]
