# Generated by Django 4.2.1 on 2023-05-17 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgr', '0003_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pgr.empresa'),
            preserve_default=False,
        ),
    ]
